title: David López Castellote
description: Programmer, Web & App developer, IT lover
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
profile-picture: david.png
cv-pdf-file: cv_es.pdf