# Theme configuration
theme: jekyll-theme-cayman
show_downloads: true
google_analytics:
title: David López Castellote
description: Programmer, Web & App developer, IT lover

# Custom configuration
profile-picture: david.png
cv-pdf-file: cv.pdf

# Internacionalization plugin
plugins: 
  - jekyll-multiple-languages-plugin

baseurl: ""
languages:  ["en", "es", "fr" ] # en is the default language